/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface PolyButton {
    'color': string;
    'disabled': boolean;
    'rounded': string;
  }
  interface PolyButtonAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'disabled'?: boolean;
    'rounded'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'PolyButton': Components.PolyButton;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'poly-button': Components.PolyButtonAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLPolyButtonElement extends Components.PolyButton, HTMLStencilElement {}
  var HTMLPolyButtonElement: {
    prototype: HTMLPolyButtonElement;
    new (): HTMLPolyButtonElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'poly-button': HTMLPolyButtonElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'poly-button': HTMLPolyButtonElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
